name: Deploy static site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip static bundle
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          rm -rf site
          mkdir site
          unzip Digital_Blood_pressuretracker_static.zip -d site
          # If the ZIP contains one top-level folder, flatten:
          shopt -s dotglob || true
          if [ "$(ls -1 site | wc -l)" -eq 1 ] && [ -d site/* ]; then
            mv site/*/* site/ 2>/dev/null || true
          fi
          # SPA fallback: copy index to 404 so client-side routes still work
          if [ -f site/index.html ] && [ ! -f site/404.html ]; then
            cp site/index.html site/404.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
